# Generated by Django 5.2.5 on 2025-11-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneBook', '0003_product_basket_featuredproduct_topproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='.'),
        ),
    ]
