# Generated by Django 5.2.5 on 2025-11-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_alter_mysuperuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysuperuser',
            name='address',
            field=models.CharField(default=None, max_length=750, null=True),
        ),
    ]
